module.exports.languageData = {
  languageData: [
    { value: "Amharic", label: "Amharic", code: "am" },
    { value: "Arabic", label: "Arabic", code: "ar" },
    { value: "Basque", label: "Basque", code: "eu" },
    { value: "Bengali", label: "Bengali", code: "bn" },
    { value: "English (UK)", label: "English (UK)", code: "en-GB" },
    {
      value: "Portuguese (Brazil)",
      label: "Portuguese (Brazil)",
      code: "pt-BR",
    },
    { value: "Bulgarian", label: "Bulgarian", code: "bg" },
    { value: "Catalan", label: "Catalan", code: "ca" },
    { value: "Cherokee", label: "Cherokee", code: "chr" },
    { value: "Croatian", label: "Croatian", code: "hr" },
    { value: "Czech", label: "Czech", code: "cs" },
    { value: "Danish", label: "Danish", code: "da" },
    { value: "Dutch", label: "Dutch", code: "nl" },
    { value: "English (US)", label: "English (US)", code: "en" },
    { value: "Estonian", label: "Estonian", code: "et" },
    { value: "Filipino", label: "Filipino", code: "fil" },
    { value: "Finnish", label: "Finnish", code: "fi" },
    { value: "French", label: "French", code: "fr" },
    { value: "German", label: "German", code: "de" },
    { value: "Greek", label: "Greek", code: "el" },
    { value: "Gujarati", label: "Gujarati", code: "gu" },
    { value: "Hebrew", label: "Hebrew", code: "iw" },
    { value: "Hindi", label: "Hindi", code: "hi" },
    { value: "Hungarian", label: "Hungarian", code: "hu" },
    { value: "Icelandic", label: "Icelandic", code: "is" },
    { value: "Indonesian", label: "Indonesian", code: "id" },
    { value: "Italian", label: "Italian", code: "it" },
    { value: "Japanese", label: "Japanese", code: "ja" },
    { value: "Kannada", label: "Kannada", code: "kn" },
    { value: "Korean", label: "Korean", code: "ko" },
    { value: "Latvian", label: "Latvian", code: "lv" },
    { value: "Lithuanian", label: "Lithuanian", code: "lt" },
    { value: "Malay", label: "Malay", code: "ms" },
    { value: "Malayalam", label: "Malayalam", code: "ml" },
    { value: "Marathi", label: "Marathi", code: "mr" },
    { value: "Norwegian", label: "Norwegian", code: "no" },
    { value: "Polish", label: "Polish", code: "pl" },
    {
      value: "Portuguese (Portugal)",
      label: "Portuguese (Portugal)",
      code: "pt-PT",
    },
    { value: "Romanian", label: "Romanian", code: "ro" },
    { value: "Russian", label: "Russian", code: "ru" },
    { value: "Serbian", label: "Serbian", code: "sr" },
    { value: "Chinese (PRC)", label: "Chinese (PRC)", code: "zh-CN" },
    { value: "Slovak", label: "Slovak", code: "sk" },
    { value: "Slovenian", label: "Slovenian", code: "sl" },
    { value: "Spanish", label: "Spanish", code: "es" },
    { value: "Swahili", label: "Swahili", code: "sw" },
    { value: "Swedish", label: "Swedish", code: "sv" },
    { value: "Tamil", label: "Tamil", code: "ta" },
    { value: "Telugu", label: "Telugu", code: "te" },
    { value: "Thai", label: "Thai", code: "th" },
    { value: "Chinese (Taiwan)", label: "Chinese (Taiwan)", code: "zh-TW" },
    { value: "Turkish", label: "Turkish", code: "tr" },
    { value: "Urdu", label: "Urdu", code: "ur" },
    { value: "Ukrainian", label: "Ukrainian", code: "uk" },
    { value: "Vietnamese", label: "Vietnamese", code: "vi" },
    { value: "Welsh", label: "Welsh", code: "cy" },
  ],
};
