module.exports.data = {
  diets: [
    { value: "gluten free", label: "Gluten Free" },
    { value: "ketogenic", label: "Ketogenic" },
    { value: "vegetarian", label: "Vegetarian" },
    { value: "lacto-vegetarian", label: "Lacto-Vegetarian" },
    { value: "ovo-vegetarian", label: "Ovo-Vegetarian" },
    { value: "vegan", label: "Vegan" },
    { value: "pescetarian", label: "Pescetarian" },
    { value: "paleo", label: "Paleo" },
    { value: "primal", label: "Primal" },
    { value: "low fodmap", label: "Low FODMAP" },
    { value: "whole30", label: "Whole30" },
  ],
  cuisines: [
    { value: "african", label: "African" },
    { value: "asian", label: "Asian" },
    { value: "american", label: "American" },
    { value: "british", label: "British" },
    { value: "cajun", label: "Cajun" },
    { value: "caribbean", label: "Caribbean" },
    { value: "chinese", label: "Chinese" },
    { value: "eastern european", label: "Eastern European" },
    { value: "european", label: "European" },
    { value: "french", label: "French" },
    { value: "german", label: "German" },
    { value: "greek", label: "Greek" },
    { value: "indian", label: "Indian" },
    { value: "irish", label: "Irish" },
    { value: "italian", label: "Italian" },
    { value: "japanese", label: "Japanese" },
    { value: "jewish", label: "Jewish" },
    { value: "korean", label: "Korean" },
    { value: "latin american", label: "Latin American" },
    { value: "mediterranean", label: "Mediterranean" },
    { value: "mexican", label: "Mexican" },
    { value: "middle eastern", label: "Middle Eastern" },
    { value: "nordic", label: "Nordic" },
    { value: "southern", label: "Southern" },
    { value: "spanish", label: "Spanish" },
    { value: "thai", label: "Thai" },
    { value: "vietnamese", label: "Vietnamese" },
  ],
  dishTypes: [
    { value: "main course", label: "Main Course" },
    { value: "side dish", label: "Side Dish" },
    { value: "dessert", label: "Dessert" },
    { value: "appetizer", label: "Appetizer" },
    { value: "salad", label: "Salad" },
    { value: "bread", label: "Bread" },
    { value: "breakfast", label: "Breakfast" },
    { value: "soup", label: "Soup" },
    { value: "beverage", label: "Beverage" },
    { value: "sauce", label: "Sauce" },
    { value: "marinade", label: "Marinade" },
    { value: "finger food", label: "Finger Food" },
    { value: "snack", label: "Snack" },
    { value: "drink", label: "Drink" },
  ],
};
